FROM python:3.9.2
LABEL maintainer = "a-ha"
ENV PATH=/root/.local/bin/:$PATH


# ADD ./Pipfile /app/
# ADD ./Pipfile.lock /app/
RUN apt update
RUN pip install pipenv
# RUN cd /app && /
# RUN pipenv install --dev --ignore-pipfile
# RUN apt install openjdk-11-jdk -y


