version: "3.8"

services:
  finance_data_lake:
    build:
      context: ..
      dockerfile: development/Dockerfile
    volumes:
      - ..:/app
    working_dir: /app/
    stdin_open: true
    tty: true
    labels:
      org.label-schema.group: "finance-data-lake"
    