version: '3.9'

services:
  finance_data_lake:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile 
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    networks:
      - "local"
  localstack:
    image: localstack/localstack:0.14.5
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DATA_DIR=/tmp/localstack/data
      # - PERSISTENCE=1
    volumes:
    - ../.cache/localstack:/tmp/localstack
      # - ../.cache/localstack:/var/lib/localstack
    networks:
      - "local"
  # dynamoDb-admin:
  #   image: aaronshaf/dynamodb-admin
  #   depends_on:
  #     - "localstack"
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - DYNAMO_ENDPOINT=http://localstack:4566
  #   networks:
  #     - "local"

networks:
  local:
    driver: bridge
